#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Usage : $0 [sheffield|london|seattle]"
    exit
fi

pushd ~/development/genymotion

./genyshell -c "gps setstatus enabled"

case "$1" in
sheffield)
    ./genyshell -c "gps setlatitude 53.3798519"
    ./genyshell -c "gps setlongitude -1.4627511"
    ;;
london)
    ./genyshell -c "gps setlatitude 51.507351"
    ./genyshell -c "gps setlongitude -0.127758"
    ;;
seattle)
    ./genyshell -c "gps setlatitude 47.608013"
    ./genyshell -c "gps setlongitude -122.335167"
    ;;
*) echo "Command name $1 not recognised"
   exit 1
   ;;
esac

popd > /dev/null
